### PR TITLE
lilPromo

### PR DESCRIPTION
**Pull request by 8chan-co**

### CODE REVIEW

**Comment by poiyomi** [comment]
Please provide a reason for the change

**Comment by 8chan-co** [comment]
English no good sorry xc

**Comment by 8chan-co** [comment]
tries to explain: approach assumed not this way! obtain from graphics specifically!
frame dimensions list first is no warrantee to be Time; time is used for frame index: therefore Time is used!

sankyu >~<

**Comment by 8chan-co** [comment]
accept PR plz >~<

**Comment by poiyomi** [comment]
PR https://github.com/Thryrallo/ThryEditor

**Comment by 8chan-co** [comment]
@Thryrallo you accept PR if me PR you changes?

**Pull request closed without merging**
